### ISSUE TITLE
802.11s DFS

### ISSUE THREAD

**Issue by vigeruno** [openNDS/mesh11sd#13]
Hello my experiments date back several years ago with 802.11s and I stopped that DFS channels could not be used.......Obviously I compiled a version that removed the DFS block which is a drastic and not legal solution. DFS problem fixed? Do radios change frequency when a radar is detected?

**Comment by bluewavenet** [comment]
@vigeruno 

> Do radios change frequency when a radar is detected?

They block transmission on channels where they have detected signals that are not identifiable as 802.11[x].
This includes radar but also interference of any kind.

DFS channels are inherently unreliable and therefore unsuitable for 802.11s use.

I live close to a remote airfield. There are two scheduled "island hopper" flights per day and the radar is turned on 15 minutes before arrival, again 15 minutes before departure, and after departure stay on until local flight controllers pass the traffic on.
This is echoed in the usability of any DFS channels I have tried to use in the past so could be regarded as functioning as designed - ie to prevent interference on radar systems.

It is probable that the wireless signal strengths are so low that radar interference would not actually occur, but I guess it is best to err on the safe side.

**Comment by bluewavenet** [comment]
@vigeruno 
In the UK it is looking a lot better:
https://www.ofcom.org.uk/consultations-and-statements/category-2/improving-spectrum-access-for-wi-fi

But I have not yet seen any suitable hardware........

**Comment by vigeruno** [comment]
> @vigeruno In the UK it is looking a lot better: https://www.ofcom.org.uk/consultations-and-statements/category-2/improving-spectrum-access-for-wi-fi
> 
> You could check if the EU has something similar.
> 
> But I have not yet seen any suitable hardware........

Yes, the 6ghz band but I don't know if legally we can use them....... I know for a fact that some local providers use it to avoid the congested 5ghz frequencies.

**Comment by vigeruno** [comment]
My idea to improve mesh networks would be to use low-cost 2x2 mimo routers at 2.4 ghz and 5 or 6 ghz but with the possibility of connecting several radios which, however, are synchronized tx-rx so as not to interfere. ..Basically a synchronization of the radios to use frequencies close to each other but without disturbing each other because they transmit and receive at the same time....I believe that there is nothing open-source yet. This should give the cue for a massive use of mesh networks which we practically do not use.

**Comment by bluewavenet** [comment]
@vigeruno 
There are some chip manufacturers that have built something similar into their designs but this is entirely proprietary.
What it produces is not a true autonomous mesh but more like a point to point extension. Most seem to be limited to a maximum of 3 devices and will not interoperate with other manufacturer's chipsets.

I have experimented with dual 5GHz radio devices using bonding between mesh channels. I used several Gl-iNet GL-MT1300 devices and it worked with no modifications required to 802.11s protocols.

What is really required in terms of hardware, is a low cost 3 radio device, 2 bonded channels for the mesh and 1 channel for the AP.

**Comment by vigeruno** [comment]
> @vigeruno There are some chip manufacturers that have built something similar into their designs but this is entirely proprietary. What it produces is not a true autonomous mesh but more like a point to point extension. Most seem to be limited to a maximum of 3 devices and will not interoperate with other manufacturer's chipsets.
> 
> I have experimented with dual 5GHz radio devices using bonding between mesh channels. I used several Gl-iNet GL-MT1300 devices and it worked with no modifications required to 802.11s protocols.
> 
> What is really required in terms of hardware, is a low cost 3 radio device, 2 bonded channels for the mesh and 1 channel for the AP.

I tried to parallel with 4 radios per side using mwan3 and 802.11s..... They work but when you bring the antennas of the 4 radios close they interfere with each other even if they use different frequencies and far apart. .... For this it would be useful to synchronize the radios in some way..... Do you think it would be possible by making some changes to the software?
