### ISSUE TITLE
Multi-hops mesh channel switching

### ISSUE THREAD

**Issue by vigeruno** [openNDS/mesh11sd#14]
Multi-hops mesh channel switching Is it supported? or is it possible to implement it?

**Comment by bluewavenet** [comment]
@vigeruno 
Sorry, I will have to ask you to explain what you mean by "Multi-hops mesh channel switching".

Normally, all nodes in a given mesh network must be operating on the same channel or frequency range. Otherwise the nodes will be unable to communicate with each other.

It is possible to implement a channel tracking function to facilitate an operational channel change and there is closed source proprietary code that implements this, but I am not at all sure if this is what you mean.

**Comment by vigeruno** [comment]
> @vigeruno Sorry, I will have to ask you to explain what you mean by "Multi-hops mesh channel switching".
> 
> Normally, all nodes in a given mesh network must be operating on the same channel or frequency range. Otherwise the nodes will be unable to communicate with each other.
> 
> It is possible to implement a channel tracking function to facilitate an operational channel change and there is closed source proprietary code that implements this, but I am not at all sure if this is what you mean.

`https://github.com/o11s/open80211s/wiki/Mesh-Channel-Switching`
`https://github.com/cozybit/iw/commit/d64a0ae1039e386304a5125614ac5f1001e977f8`

**Comment by bluewavenet** [comment]
@vigeruno 
As far as I am aware, this was never implemented outside of o11s, certainly not in OpenWrt.
Note o11s appears to be defunct with no updates for over 10 years as far as I can tell.

**Comment by vigeruno** [comment]
> @vigeruno As far as I am aware, this was never implemented outside of o11s, certainly not in OpenWrt. Note o11s appears to be defunct with no updates for over 10 years as far as I can tell.

Do you think we can be able to make the channel change on command? It would be very useful

**Comment by bluewavenet** [comment]
@vigeruno 
There is a proprietary, closed source package that includes that functionality.
The mesh11sd package is based on open-sourced parts of this.
The Blue-Wave company will have to consider if the "channel changing" code could be open-sourced as well.

**Comment by bluewavenet** [comment]
@vigeruno 
mesh11sd v2.0.0 is released and available in the OpenWrt master branch. The build system bots are slowly rolling it out to 23.05 and 22.03.

This version supports remote admin via the mesh11sd command line.
So it is possible to do your own scripting to change the channel in the config of every meshnnode and once all are done, reboot, restart network or run the `wifi` command on each meshnode in turn ( from the most remote first ). You could set a timer to restart  each meshnode automatically, giving enough time to change them all, to make sure you do not isolate a section of mesh.

**Comment by bluewavenet** [comment]
@vigeruno 
**Channel tracking** is now implemented and the pre-release beta (v2.1.0beta) can be made available for testing if you are interested ;-)

**Comment by bluewavenet** [comment]
@vigeruno 
Note: This is **autonomous** channel tracking. The portal meshnode ( the one with an upstream link ) will have a "static" channel configured.
All the peer nodes will autonomously track whatever channel the portal node is using.
In effect, a channel change will ripple out into the mesh from the portal node.

**Comment by vigeruno** [comment]
> @vigeruno **Channel tracking** is now implemented and the pre-release beta (v2.1.0beta) can be made available for testing if you are interested ;-)

Yes thanks I'm interested in doing tests.....

**Comment by bluewavenet** [comment]
@vigeruno 
The pre-release beta is here:
https://github.com/openNDS/mesh11sd/releases/tag/v3.0.0-beta

**Comment by bluewavenet** [comment]
@vigeruno 
I bumped to v3.0.0 as there are major additions over previous versions.
