### ISSUE TITLE
Is it not required to update the mesh11s configuration also to wpa_supplicant.conf ?

### ISSUE THREAD

**Issue by Sophronia-AK** [openNDS/mesh11sd#22]
Mesh11sd takes care of updating the configuration directly to the driver via "iw" utility, is it not required to update them to wpa_supplicant.conf ?
For eg: configuration like, max_peer_links

**Comment by bluewavenet** [comment]
@Sophronia-AK 

> is it not required to update them to wpa_supplicant.

No. wpa_supplicant-[interface].conf is generated at wireless startup from the uci `/etc/config/wireless` configuration.
Whereas mesh11sd writes to the driver via `iw`, and can do this dynamically at any time, not just at startup.

If you want to see the active mesh parameters do:
`mesh11sd status`

**Comment by Sophronia-AK** [comment]
@bluewavenet  Thank you for the response
