### ISSUE TITLE
WPA2/WPA3 Personal (PSK/SAE) mixed mode wrong value

### ISSUE THREAD

**Issue by Anderl94** [openNDS/mesh11sd#78]
If I set mesh_gate_encryption to "2", mesh11sd sets the encryption to "sae-mixed+aes". This setting does not exist according to the OpenWrt wiki.

**Comment by bluewavenet** [comment]
@Anderl94 

> "sae-mixed+aes". This setting does not exist according to the OpenWrt wiki.

Oh indeed, it is not in the wiki, I did not notice that. It is valid though. AFAIK it inhibits legacy clients trying to use TKIP cypher on WPS2
